version: '2.1'

volumes:
  gitlab_data:
    driver: local
  gitlab_logs:
    driver: local
  gitlab_config:
    driver: local
  redis_data:
    driver: local
  db-data:
    driver: local

services:

  gitlab:
    restart: always
    image: gitlab/gitlab-ce:11.8.2-ce.0
    container_name: gitlab
    env_file:
      .env
    volumes:
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/var/log/gitlab
      - ./gitlab-conf/gitlab.rb:/etc/gitlab/gitlab.rb
      - ./cron:/var/spool/cron/crontabs

  nginx:
    restart: always
    image: ${REGISTRY}optimum/nginx-le:stable
    container_name: nginx
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs/ssl:/etc/ssl/nginx
      - ./certs/letsencrypt:/etc/letsencrypt
      - ./cron/nginx:/var/spool/cron/crontabs
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./null:/etc/nginx/sites-enabled
      - ./supervisord/nginx.conf:/etc/supervisor/conf.d/nginx.conf
    links:
      - gitlab
    entrypoint: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n

  status:
    image: ${REGISTRY}trydirect/status
    container_name: docker_status_panel
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./nginx:/app/destination_conf
      - ./nginx_original:/app/origin_conf
      - ./config.json:/app/config.json
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
